services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    blackbit\BackupBundle\Command\BackupCommand:
        arguments:
            $filesystemAdapter: '@blackbit.backup.adapter'
        tags: ['console.command']

    blackbit\BackupBundle\Command\RestoreCommand:
        arguments:
            $filesystemAdapter: '@blackbit.backup.adapter'
        tags: [ 'console.command' ]

    blackbit\BackupBundle\Command\SyncCommand:
        tags: [ 'console.command' ]

    blackbit.backup.adapter:
        class: League\Flysystem\Local\LocalFilesystemAdapter
        arguments:
            $location: '/tmp'

    League\Flysystem\AdapterInterface: '@blackbit.backup.adapter'